[phases.setup]
aptPkgs = [
    'libglib2.0-0',
    'libsm6', 
    'libxext6', 
    'libxrender1', 
    'libgomp1',
    'libgl1-mesa-glx',
    'libglib2.0-dev',
    'libgtk-3-dev',
    'libavcodec-dev',
    'libavformat-dev',
    'libswscale-dev',
    'libgstreamer-plugins-base1.0-dev',
    'libgstreamer1.0-dev',
    'libpng-dev',
    'libjpeg-dev',
    'libopenexr-dev',
    'libtiff-dev',
    'libwebp-dev',
    'ffmpeg'
]

[variables]
OPENCV_IO_ENABLE_OPENEXR = '0'
QT_QPA_PLATFORM = 'offscreen'
MPLBACKEND = 'Agg'
PYTHONUNBUFFERED = '1'
DEBIAN_FRONTEND = 'noninteractive'

[start]
cmd = 'python main.py'
