services:
  - type: web
    name: yolov8-deskew-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    port: 5000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12

routes:
  - type: static
    path: /processed
    dir: processed
static:
  - name: processed
    path: static/processed
