services:
  - type: web
    name: yolov8-deskew-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

static:
  - name: processed
    path: static/processed
